-- SQL statements to add new columns to existing MULTISTEP_USER table

-- Add GENDER column
ALTER TABLE MULTISTEP_USER ADD GENDER VARCHAR2(20);

-- Add DOB column
ALTER TABLE MULTISTEP_USER ADD DOB VARCHAR2(50);

-- Add ACCOUNT_TYPE column
ALTER TABLE MULTISTEP_USER ADD ACCOUNT_TYPE VARCHAR2(50);

-- Add NEWSLETTER column (1 = true, 0 = false)
ALTER TABLE MULTISTEP_USER ADD NEWSLETTER NUMBER(1);

-- Add COMPANY_NAME column
ALTER TABLE MULTISTEP_USER ADD COMPANY_NAME VARCHAR2(200);

-- Add COMPANY_SIZE column
ALTER TABLE MULTISTEP_USER ADD COMPANY_SIZE VARCHAR2(50);

-- Add FILE_NAME column
ALTER TABLE MULTISTEP_USER ADD FILE_NAME VARCHAR2(255);

-- Add FILE_PATH column
ALTER TABLE MULTISTEP_USER ADD FILE_PATH VARCHAR2(500);

-- Update existing records with default values (optional)
-- UPDATE MULTISTEP_USER SET GENDER = 'Not Specified' WHERE GENDER IS NULL;
-- UPDATE MULTISTEP_USER SET DOB = '01-01-2000' WHERE DOB IS NULL;

-- Verify the changes
DESC MULTISTEP_USER;

-- Sample INSERT with new fields
INSERT INTO MULTISTEP_USER (ID, FULL_NAME, EMAIL, MOBILE, GENDER, DOB, ADDRESS, CITY, STATE, USERNAME, PASSWORD)
VALUES (MULTISTEP_SEQ.NEXTVAL, 'John Doe', 'john@example.com', '9876543210', 'Male', '1995-05-15', '123 Main St', 'Mumbai', 'Maharashtra', 'johndoe', 'password123');

COMMIT;
